language: java

addons:
  sonarcloud:
    organization: "jackgoldsworth-github"
    token:
      secure: "N82YXJu9CM0LI6urmXm6cdqTGUHDzIErieMC7KKcnrcR8Fr8hnjFbUONCUBFDDEUxHOKClJ8SdgPJdmbv2gX+e1Ycnlo/Z6gWvnJLGYQPM6c6Unzt10nlFNOahu09bRvFBlCO/IyZxz21W24IUlbmGHZRXf+O3Pm9wOPMXcaeLof+xnekWAuDDFca9CHGSBTwyGDD3eCou6y2AO5L76vCrrkiOGJuaUzqYytoftPm9QR0NIIpJns5gkyFoxrtXWczjWlP0jh48z6v09W1ArPGzSG6KU/8gt7Ln6RNC1HO/BFMxeyMUV7M0U9n//dMPhkAjPHLprXja3IO0LNzgrGDPp3j35IWnCrsZ6bq795s6QkDBBzBWCBB/gtXEIWyEbRJd8HXR8wVyX/tZgdJMZrydI5a2Vy8TQlRbv5ElDlPLP0HKbfmAdcpQkqaNNKAPC899HYNC1f0XobP33bRmSF3VqVBKWNcKxrjL9kQt/VJ/kYalDRSCrD/AApEt/+X6Xq/WvoW7OI1LyPq62JmMB8ztx7LoU+pLZQ8ld9oERRS4CpSo/MNSu3rd0jK9rAsbOoRwQZXlpjnxbORq23x1XkyFmmfVxIRdi29buiUA0FsveBLplhNsHThSAVJ2Nj2orlJ//mKYXEcsxdoODGzl2FhL6ZDAAOSAS0wfmGurL45PE="

jdk:
  - oraclejdk8

install:
  - true

script:
  - "./gradlew sonarqube"

after_script:
  - "bash changelog.sh"
after_failure:
  - "./gradlew notifyIfError"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'